# Generated by Django 2.0.7 on 2018-07-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publish', models.IntegerField()),
                ('author', models.CharField(max_length=250)),
                ('resume', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('pushised_data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('resume', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('pushised_data', models.DateTimeField(blank=True, null=True)),
                ('id_publish', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publish', models.IntegerField()),
                ('author', models.CharField(max_length=250)),
                ('resume', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('pushised_data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publish', models.IntegerField()),
                ('author', models.CharField(max_length=250)),
                ('resume', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('pushised_data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
