# Generated by Django 2.0.7 on 2018-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='pushised_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
