# Generated by Django 2.0.7 on 2018-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180727_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='id_publish',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
