# Generated by Django 2.0.7 on 2018-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180727_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='text',
            new_name='resume',
        ),
    ]
